// Autogenerated from Pigeon (v21.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLUTTERVolume;

@interface FLUTTERVolume : NSObject
+ (instancetype)makeWithValue:(nullable NSNumber *)value;
@property(nonatomic, strong, nullable) NSNumber * value;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *FLUTTERGetCodec(void);

@protocol FLUTTERVolumeApi
/// @return `nil` only when `error != nil`.
- (nullable FLUTTERVolume *)getVolumeDeviceWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpFLUTTERVolumeApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLUTTERVolumeApi> *_Nullable api);

extern void SetUpFLUTTERVolumeApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLUTTERVolumeApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
